version: '3.8'

services:

  postgresql:
    container_name: postgresql_django
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: ./data
      o: bind
