version: '3.8'

services:

  django:
    container_name: django
    build:
      context: ./django
      dockerfile: Dockerfile.prod
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./django/.env.prod
    depends_on:
      - postgresql

  postgresql:
    container_name: postgresql
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./postgresql/.env.prod

  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - django

volumes:
  postgres_data:
  static_volume: