version: '3.8'

services:

  django:
    container_name: django_dev
    build:
      context: ./django
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - django_srcs:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./django/.env.dev

  llm:
    container_name: llm
    build:
        context: ./llm
        dockerfile: Dockerfile
    ports:
      - 6000:3000

  postgresql:
    container_name: postgresql_dev
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./postgresql/.env.dev

volumes:
  django_srcs:
    driver: local
    driver_opts:
      type: none
      device: ./django
      o: bind
  postgres_data:

