FROM python:3.11.4-slim-buster

WORKDIR /usr/src/app

RUN apt update
RUN apt upgrade -y
RUN apt install -y netcat

# PYTHONDONTWRITEBYTECODE : Prevents Python from writing pyc files to disc
ENV PYTHONDONTWRITEBYTECODE 1
# PYTHONUNBUFFERED : Prevents Python from buffering stdout and stderr
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# copy entrypoint.dev.sh
COPY ./entrypoint.dev.sh .
RUN chmod +x /usr/src/app/entrypoint.dev.sh

# copy project
COPY . .

ENTRYPOINT ["/usr/src/app/entrypoint.dev.sh"]
