# Generated by Django 5.0.4 on 2024-04-23 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='homeworld',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ex09.planets'),
        ),
        migrations.AlterField(
            model_name='planets',
            name='climate',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='planets',
            name='diameter',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='planets',
            name='orbital_period',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='planets',
            name='population',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='planets',
            name='rotation_period',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='planets',
            name='surface_water',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='planets',
            name='terrain',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
